Traceback (most recent call last):
  File "train.py", line 20, in <module>
    import utils.import_envs  # pytype: disable=import-error
  File "/home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/16_stable_baselines/6_stable_baselines_zoo/rl-baselines-zoo/utils/__init__.py", line 1, in <module>
    from .utils import make_env, ALGOS, linear_schedule, create_test_env,\
  File "/home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/16_stable_baselines/6_stable_baselines_zoo/rl-baselines-zoo/utils/utils.py", line 18, in <module>
    from stable_baselines.deepq.policies import FeedForwardPolicy
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/stable_baselines/__init__.py", line 1, in <module>
    from stable_baselines.a2c import A2C
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/stable_baselines/a2c/__init__.py", line 1, in <module>
    from stable_baselines.a2c.a2c import A2C
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/stable_baselines/a2c/a2c.py", line 5, in <module>
    import tensorflow as tf
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/framework_lib.py", line 52, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 28, in <module>
    from tensorflow.python.framework import function
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/function.py", line 36, in <module>
    from tensorflow.python.ops import array_ops
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 30, in <module>
    from tensorflow.python.framework import constant_op
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 32, in <module>
    from tensorflow.python.eager import execute
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 23, in <module>
    from google.protobuf import text_format
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/google/protobuf/text_format.py", line 1191, in <module>
    class Tokenizer(object):
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/google/protobuf/text_format.py", line 1209, in Tokenizer
    for mark in _QUOTES
  File "/home/pierre/bin/anaconda3/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/home/pierre/bin/anaconda3/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/pierre/bin/anaconda3/lib/python3.7/sre_compile.py", line 768, in compile
    code = _code(p, flags)
  File "/home/pierre/bin/anaconda3/lib/python3.7/sre_compile.py", line 607, in _code
    _compile(code, p.data, flags)
  File "/home/pierre/bin/anaconda3/lib/python3.7/sre_compile.py", line 209, in _compile
    _compile(code, av, flags)
  File "/home/pierre/bin/anaconda3/lib/python3.7/sre_compile.py", line 120, in _compile
    charset, hascased = _optimize_charset(av, iscased, tolower, fixes)
  File "/home/pierre/bin/anaconda3/lib/python3.7/sre_compile.py", line 364, in _optimize_charset
    data = _mk_bitmap(charmap)
  File "/home/pierre/bin/anaconda3/lib/python3.7/sre_compile.py", line 411, in _mk_bitmap
    def _mk_bitmap(bits, _CODEBITS=_CODEBITS, _int=int):
KeyboardInterrupt
