/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    import utils.import_envs  # pytype: disable=import-error
  File "/home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/16_stable_baselines/6_stable_baselines_zoo/rl-baselines-zoo/utils/__init__.py", line 1, in <module>
    from .utils import make_env, ALGOS, linear_schedule, create_test_env,\
  File "/home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/16_stable_baselines/6_stable_baselines_zoo/rl-baselines-zoo/utils/utils.py", line 18, in <module>
    from stable_baselines.deepq.policies import FeedForwardPolicy
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/stable_baselines/__init__.py", line 4, in <module>
    from stable_baselines.deepq import DQN
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/stable_baselines/deepq/__init__.py", line 1, in <module>
    from stable_baselines.deepq.policies import MlpPolicy, CnnPolicy, LnMlpPolicy, LnCnnPolicy
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/stable_baselines/deepq/policies.py", line 2, in <module>
    import tensorflow.contrib.layers as tf_layers
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/__init__.py", line 41, in <module>
    from tensorflow.contrib import distributions
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/distributions/__init__.py", line 44, in <module>
    from tensorflow.contrib.distributions.python.ops.estimator import *
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/distributions/python/ops/estimator.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/__init__.py", line 93, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/__init__.py", line 28, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 302, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 34, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 36, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 52, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 26, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 33, in <module>
    import dask.dataframe as dd
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/dask/__init__.py", line 6, in <module>
    from .delayed import delayed
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/dask/delayed.py", line 8, in <module>
    from cytoolz import curry, concat, unique, merge
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/cytoolz/__init__.py", line 1, in <module>
    from .itertoolz import *
  File "cytoolz/itertoolz.pyx", line 19, in init cytoolz.itertoolz
  File "cytoolz/utils.pyx", line 10, in init cytoolz.utils
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/toolz/__init__.py", line 18, in <module>
    from . import curried, sandbox
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/toolz/curried/__init__.py", line 27, in <module>
    from . import operator
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/toolz/curried/operator.py", line 15, in <module>
    for name, f in vars(operator).items() if callable(f)},
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/toolz/curried/operator.py", line 15, in <dictcomp>
    for name, f in vars(operator).items() if callable(f)},
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/toolz/curried/operator.py", line 9, in should_curry
    num = num_required_args(f)
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/toolz/functoolz.py", line 884, in num_required_args
    func)
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/toolz/functoolz.py", line 832, in _check_sigspec
    sigspec = inspect.signature(func)
  File "/home/pierre/bin/anaconda3/lib/python3.7/inspect.py", line 3083, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/home/pierre/bin/anaconda3/lib/python3.7/inspect.py", line 2833, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/home/pierre/bin/anaconda3/lib/python3.7/inspect.py", line 2288, in _signature_from_callable
    skip_bound_arg=skip_bound_arg)
  File "/home/pierre/bin/anaconda3/lib/python3.7/inspect.py", line 2114, in _signature_from_builtin
    return _signature_fromstr(cls, func, s, skip_bound_arg)
  File "/home/pierre/bin/anaconda3/lib/python3.7/inspect.py", line 1968, in _signature_fromstr
    _signature_strip_non_python_syntax(s)
  File "/home/pierre/bin/anaconda3/lib/python3.7/inspect.py", line 1921, in _signature_strip_non_python_syntax
    for t in token_stream:
  File "/home/pierre/bin/anaconda3/lib/python3.7/tokenize.py", line 508, in _tokenize
    line = readline()
KeyboardInterrupt
