/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    import utils.import_envs  # pytype: disable=import-error
  File "/home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/16_stable_baselines/6_stable_baselines_zoo/rl-baselines-zoo/utils/__init__.py", line 1, in <module>
    from .utils import make_env, ALGOS, linear_schedule, create_test_env,\
  File "/home/pierre/HDD/0_Complearn/1_learning/0_Reinforcement_learning/16_stable_baselines/6_stable_baselines_zoo/rl-baselines-zoo/utils/utils.py", line 18, in <module>
    from stable_baselines.deepq.policies import FeedForwardPolicy
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/stable_baselines/__init__.py", line 4, in <module>
    from stable_baselines.deepq import DQN
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/stable_baselines/deepq/__init__.py", line 1, in <module>
    from stable_baselines.deepq.policies import MlpPolicy, CnnPolicy, LnMlpPolicy, LnCnnPolicy
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/stable_baselines/deepq/policies.py", line 2, in <module>
    import tensorflow.contrib.layers as tf_layers
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/__init__.py", line 41, in <module>
    from tensorflow.contrib import distributions
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/distributions/__init__.py", line 44, in <module>
    from tensorflow.contrib.distributions.python.ops.estimator import *
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/distributions/python/ops/estimator.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/__init__.py", line 93, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/__init__.py", line 28, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 40, in <module>
    from tensorflow.contrib.learn.python.learn.experiment import Experiment
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 39, in <module>
    from tensorflow.contrib.tpu.python.tpu import tpu_estimator
  File "/home/pierre/bin/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/tpu/__init__.py", line 78, in <module>
    from tensorflow.contrib.tpu.python.tpu.tpu_estimator import *
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
  File "<frozen importlib._bootstrap>", line 148, in __enter__
  File "<frozen importlib._bootstrap>", line 174, in _get_module_lock
  File "<frozen importlib._bootstrap>", line 62, in __init__
KeyboardInterrupt
